### ISSUE TITLE
.annotation as column name

### ISSUE THREAD

**Issue by PappasChristoforos** [the-Hull/datacleanr#7]
In case in the data.frame imported to datacleanr there is already a column called '.annotation' (for example when using the application in a 'sequential mode' and doing 'back-and-forth' in data processing), then the selected data points/outliers, will be identified in a column called '.annotation.y' and the original '.annotation' column will be renamed to '.annotation.x'. Thus, the following line in the proposed code for excluding data points obtained from the 'Extract' tab:

```r
# DR_df_lg  <- DR_df_lg %>% dplyr::filter(is.na(.annotation))
```
has to be modified to 

```r
# DR_df_lg  <- DR_df_lg %>% dplyr::filter(is.na(.annotation.y))
```

**Comment by the-Hull** [comment]
Added a check for this, with a prompt to adjust the column name when launching `dcr_app()`. See https://github.com/the-Hull/datacleanr/commit/1e3f6e622658f7867424dfdf939ba0dae510b8db for details.
